Initial implementation
epiphany-platform/m-istio pull request #1
Opened 2020-12-18 14:42 UTC by seriva

Initial implementation:

- Tested on AKS, EKS basic settings with demo application on top.
- For EKS used this [pull](https://github.com/epiphany-platform/m-aws-kubernetes-service/pull/30) and set node size to m.medium.

Needs:
- Testing of HUB setting with self hosted/provided docker repo. 
- Some more sanity checks

2020-12-22 12:20 UTC, rpudlowski93 commented on resources/templates.mk
> +       istioNamespace: $(M_ISTIO_NAMESPACE)
I think, we need to add here hub parameter in order to make possible using external/provided custom hub with images also for istio (control plane, proxy etc..). In istioctl, flag : --hub is related only to istio operator.

2020-12-28 08:57 UTC, seriva commented on resources/templates.mk
> +       istioNamespace: $(M_ISTIO_NAMESPACE)
Yes I will be adding that today:)

2020-12-28 12:53 UTC, seriva commented on resources/templates.mk
> +       istioNamespace: $(M_ISTIO_NAMESPACE)
Fixed.

2021-01-04 16:03 UTC, rpudlowski93 commented on README.md
> +  docker run --rm -v /tmp/shared:/shared -t epiphanyplatform/Istio:latest init
I think that repository name must be lowercase

2021-01-04 16:24 UTC, rpudlowski93 commented
Great job! I tested it on AKS and everything works fine :)

2021-01-05 05:19 UTC, atsikham requested changes
I'm verifying the default installation in EKS, will report status later.

2021-01-05 05:19 UTC, atsikham commented on README.md
> +- [Azure Kubernetes Servicee](https://github.com/epiphany-platform/m-azure-kubernetes-service#run-module)
```suggestion
- [Azure Kubernetes Service](https://github.com/epiphany-platform/m-azure-kubernetes-service#run-module)
```

2021-01-05 05:19 UTC, atsikham commented on README.md
> +  cd m-aws-basic-infrastructure/
```suggestion
  cd m-istio/
```

2021-01-05 06:41 UTC, atsikham requested changes

2021-01-05 06:41 UTC, atsikham commented on README.md
> +  docker run --rm -v /tmp/shared:/shared -t epiphanyplatform/Istio:latest init
It at least in lowercase on the build stage

2021-01-05 06:43 UTC, atsikham commented
Do we need to exclude some files from Docker build context? There is no `.dockerignore` now.

2021-01-05 06:54 UTC, atsikham commented
After a [fix](https://github.com/epiphany-platform/m-aws-kubernetes-service/pull/35) in AWS KS module I was able to rebuild EKS image and then deployed a default configuration on EKS.
![image](https://user-images.githubusercontent.com/6271862/103615349-434a8c80-4f4c-11eb-8cb1-f8114e9ff179.png)

2021-01-05 07:17 UTC, seriva commented on README.md
> +  docker run --rm -v /tmp/shared:/shared -t epiphanyplatform/Istio:latest init
Fixed:)

2021-01-05 07:22 UTC, seriva commented
> Do we need to exclude some files from Docker build context? There is no `.dockerignore` now.

Ill check it.

2021-01-05 07:22 UTC, seriva commented
> After a [fix](https://github.com/epiphany-platform/m-aws-kubernetes-service/pull/35) in AWS KS module I was able to rebuild EKS image and then deployed a default configuration on EKS.
> ![image](https://user-images.githubusercontent.com/6271862/103615349-434a8c80-4f4c-11eb-8cb1-f8114e9ff179.png)

Jup I ran into the same issue yesterday and made the same fix:D

2021-01-05 08:16 UTC, seriva commented
> > Do we need to exclude some files from Docker build context? There is no `.dockerignore` now.
> 
> Ill check it.

Added dockerignore.

2021-01-05 10:16 UTC, mkyc requested changes

2021-01-05 10:16 UTC, mkyc commented on workdir/Makefile
> +export AWS_SECRET_ACCESS_KEY=$(M_AWS_SECRET_KEY)
why do we need it?

2021-01-05 10:16 UTC, mkyc commented on README.md
> +  ARM_TENANT_ID ?= "tenant field"
why do I need those values in this module?

2021-01-05 10:16 UTC, mkyc commented on docs/INPUTS.adoc
> +(Only needed when using an EKS cluster)
why do I need those values in this module?

2021-01-05 17:53 UTC, seriva commented on README.md
> +**Note : The ```M_AWS_ACCESS_KEY``` and ```M_AWS_SECRET_KEY``` environment variables are only needed for EKS**
In order to use the kubeconf generated by EKS for both istioctl and kubectl you need AWS cli which in turn needs the credentials:

![1](https://user-images.githubusercontent.com/11056665/103680855-1071ba00-4f87-11eb-9371-9184c2d8c5c4.png)
![2](https://user-images.githubusercontent.com/11056665/103680860-123b7d80-4f87-11eb-99c3-9d205feb57dd.png)

Tested both from module and normal install.

2021-01-05 17:54 UTC, seriva commented on workdir/Makefile
> +export AWS_SECRET_ACCESS_KEY=$(M_AWS_SECRET_KEY)
See comment here: https://github.com/epiphany-platform/m-istio/pull/1#discussion_r552094827

2021-01-05 17:54 UTC, seriva commented on README.md
> +  ARM_TENANT_ID ?= "tenant field"
See comment here: https://github.com/epiphany-platform/m-istio/pull/1#discussion_r552094827

2021-01-05 17:55 UTC, seriva commented on docs/INPUTS.adoc
> +(Only needed when using an EKS cluster)
See comment here: See comment here: https://github.com/epiphany-platform/m-istio/pull/1#discussion_r552094827

2021-01-05 18:06 UTC, seriva commented
> > Do we need to exclude some files from Docker build context? There is no `.dockerignore` now.
> 
> Ill check it.

Added `.dockerignore`

2021-01-07 14:21 UTC, rpudlowski93 commented on README.md
> +**Note : The ```M_AWS_ACCESS_KEY``` and ```M_AWS_SECRET_KEY``` environment variables are only needed for EKS**
Indeed I also remember that in contrary to Azure/AKS, You need to have configured aws using credential in order to use kubectl with kubeconf generatred by EKS.  I think that there is a way to run kubectl without passing the credentials but the kubeconfig must be updated as it is mentioned here [link](https://docs.aws.amazon.com/eks/latest/userguide/create-kubeconfig.html). For our usage I suppose that this way which Luuk implemented is enough.

2021-01-07 14:23 UTC, rpudlowski93 approved these changes
LGTM 👍

2021-01-07 15:13 UTC, mkyc commented on README.md
> +**Note : The ```M_AWS_ACCESS_KEY``` and ```M_AWS_SECRET_KEY``` environment variables are only needed for EKS**
I added issue #2 to reconsider it in future.

2021-01-07 15:14 UTC, mkyc commented on README.md
> +  ARM_TENANT_ID ?= "tenant field"
Wait a sec, those are for AKS not EKS.

2021-01-07 15:24 UTC, seriva commented on README.md
> +  ARM_TENANT_ID ?= "tenant field"
Ahh I see, it's running of examples which need the deploy BI and AKS first.

2021-01-07 15:27 UTC, mkyc commented on README.md
> +  ARM_TENANT_ID ?= "tenant field"
Ahhh .... ok, I didn't notice that it's about examples. I believe we will need to make documentation more clear about it in future, but for now it's OK.

2021-01-07 15:28 UTC, mkyc approved these changes
LGTM

2021-01-08 07:32 UTC, atsikham approved these changes

2021-01-08 07:35 UTC, merged